spring:
  cloud:
    gateway:
      routes:
        - id: Admin-Service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
          filters:
            - AuthenticationFilter
          
        - id: Identity-Service
          uri: lb://IDENTITY-SERVICE
          predicates: 
            - Path=/auth/**
            
        - id: User-Data-Service
          uri: lb://USER-DATA-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
            
      globalcors:
        add-to-simple-url-handler-mapping: true

        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "User-Key"
              - "Request-Tracker"
              - "Session-Tracker"
              - "X-XSRF-TOKEN"
              - "X-IBM-CLIENT-ID"
              - "Message-ID"
              - "X-IBM-CLIENT-SECRET"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
server:
  port: 8070
  